version: '2'
networks:
  bridge:
    driver: bridge

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_hotels_search
    volumes:
      - mongo-db:/data
    ports:
      - '27017:27017'

  mongo-express:
    container_name: mongo-express
    image: mongo-express_hotels_search
    links:
      - 'mongodb:mongo'
    ports:
      - '8081:8081'
volumes:
  mongo-db:
    driver: local
